### ISSUE TITLE
Able to use keys that do not match the configuration 100%.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#139]
CrateReloaded v1.3.97

You are able to use keys that do not match the crate configuration 100%. 

```
    key:
        item: 'Tripwire_Hook'
        enchantment: '300:1'
        name: '&fHat &6Key!'
        lore: 
            - '&7Use on the chest at spawn!'
```

A staff member of mine obtained a key when teleporting to another world (void) and didn't know how he got it. Looking into the key, it does not match the configuration 100% but registers with CrateReloaded for creative control. The key is missing an NBT tag (glow enchant). Would it be possible to only allow for keys that 100% match the configuration so players can't custom name / lore a key similarly to 'obtain' a key illegitimately?

Legitimate key spawned in via ```/cr givekey```
![link](http://i.imgur.com/7sGB4Ll.png)

Unknown illegitimately obtained / found key?
![link2](http://i.imgur.com/oCerqS0.png)
