### ISSUE TITLE
Crate Animation

### ISSUE THREAD

**Issue by WizzleBear** [Hazebyte/CrateReloaded#166]
I understand people complained about the old animation being too long, but I think the new animation is a bit bland. I think there should be an option to enable the old one and the new one.

**Comment by imWillX** [comment]
Sure thing, we're restructuring the plugin right now. As you noticed, we changed it so we have an animation key in the crate.yml.

We'll also add in an end-animation key as well to compromise.

**Comment by WizzleBear** [comment]
When do you think 2.0 will be released?

**Comment by imWillX** [comment]
No ETAs but I have a feeling that we'll have a public build in April.

**Comment by imWillX** [comment]
Finished initial work on this. Two endings are BLANK and RANDOM
```
 FoodKey:
     type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
     item: '399 1 name:&c[&6Foodie_Key&c]_&f#1 lore:&7Mmmm,_something_smells_good.|&8Right_click_a_chest_to_receive_a_pack_of_food! glow:true'
     animation: 'CSGO'
     ending: 'RANDOM'
```
