### ISSUE TITLE
Reward Groups

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#201]
Suggestion is to add a feature to crates where you can group rewards which have their own custom chances and min/max reward chances. 

This will allow for the creation of systems such as guarenteed rewards, random rewards, and guarenteed&&random rewards all from 1 crate.

```
ExampleChest:
    type: MYSTERYCRATE
    message:
        onOpen: '%prefix% You opened an &c&lExample Chest&f:'
    item:
        name: '*** Example Chest ***'
        lore:
            - '&7Mmmm, something smells like an example'
            - '&8Right-click this chest in your hand to obtain great examples!'
    rewards:
        group1:
          minRewards: 2
          maxRewards: 2
            - 'cmd:(/give %player% diamond 1 name:guarenteed), chance:(100), noduplicate:()'
            - 'cmd:(/give %player% dirt 2 name:guarenteed), chance:(100), noduplicate:()'
        group2:
          minRewards: 1
          maxRewards: 5
            - 'cmd:(/give %player% emerald 3 name:rando), chance:(25), noduplicate:()'
            - 'cmd:(/give %player%  grass 1 name:rando), chance:(75), noduplicate:()'
            - 'cmd:(/give %player% trapdoor 1 name:rando), chance:(55), noduplicate:()'
            - 'cmd:(/give %player% diamond 1 name:rando), chance:(25), noduplicate:()'
            - 'cmd:(/eco give %player% 1000), chance:(35), noduplicate:()'
        group3:
          minRewards: 1
          maxRewards: 1
            - 'cmd:(/give %player% diamondblock 10 name:randoguarenteed), chance:(15), noduplicate:()'
            - 'cmd:(/give %player% emeraldblock 10 name:randoguarenteed), chance:(35), noduplicate:()'
            - 'cmd:(/give %player% goldblock 10 name:randoguarenteed), chance:(55, noduplicate:()'
            - 'cmd:(/give %player% ironlock 10 name:randoguarenteed), chance:(75), noduplicate:()'

```

When the player uses this mysterycrate, he will receive the following:

1x Diamond (group1)
2x Dirt          (group1)

3x Emerald (g2)
1x Trapdoor (g2)

10x GoldBlock

where group1 are guarenteed rewards, group2 is random rewards, and group 3 is guarenteed && random.
 Obviously there are a ton more uses for this than what is in this post, but it is just a suggestion, as it makes the reward system much more powerful.

With the current crates setup, the only (logical) way to achieve this same system is to have this first crate + 3 separate crates.
