### ISSUE TITLE
Separate directory for crates

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#211]
Wanted to suggest adding a crates directory where we could split up crates into their own files. This becomes useful for people (like me) who have a crate or two with ~4,000 rewards.

To keep it versatile, make it where the user needs to generate the file to use it, that way it doesn't:
1. Cause issues when a file hits 10k lines (have had this issue before)
2. Keeps things organized
 --------

In crates.yml, you could inherit a deluxemenus type system, where crates.yml has 

```
Crates:
  crate1:
    file: crate1.yml
# name of this crate for use in commands will be "Crate1"
```
