### ISSUE TITLE
[Feature Request] Completely disable Preview-Menu on 1 page crates

### ISSUE THREAD

**Issue by DJ411** [Hazebyte/CrateReloaded#216]
I would like to enable or disable the preview-menu buttons. Or have them disabled if there is no need to have it with a small number of rows.

**Comment by imWillX** [comment]
```
preview-menu:
    name: 'Crates'
    buttons-enabled: true
    next-button: '262 1 &aNext_Page &eClick_to_enter_the_next_page.'
    close-button: '2259 1 &4Close!'
    back-button: '355 1 &4&lGo_back! &eGo_back_to_previous_page.'
```
