### ISSUE TITLE
[Feature Request] Add option to set pitch for sound

### ISSUE THREAD

**Issue by DMEpepperoni** [Hazebyte/CrateReloaded#244]
Recently I was looking into setting the sound for my crate opening (csgo style) and I haven't found an option to set the pitch of the sound.

I think it would be a great idea to add the option to specify the pitch.

**Comment by imWillX** [comment]
This is now possible. 

Example:
```
        2:
          class: Sound
          category: OPEN
          sound: BLOCK_WOOD_PLACE
          soundVolume: 100F
          soundPitch: 1.0F
```
