### ISSUE TITLE
Re-implement "cratename" placeholder.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#251]
CrateReloaded 2.0 ALPHA (published build)

```
# Received a crate
crate.player.received=%prefix%You have received a crate.
# Received a key
crate.player.keyreceived=%prefix%You have received a key
```

These two messages in 1.x have been merged into one in 2.x.

```
core.player_given_crate = {p} &eYou have been given {number} {crate}
```

Would it be possible to re-add the placeholder {crate_name} where it uses the displayname configured as the name of the crate in the message? That way I could update the message to something like;

```
core.player_given_crate = {p} &eYou have received {number} {crate_display} keys!
```

Related issue: https://github.com/Hazebyte/CrateReloaded/issues/245
Use to be able to display the customized name of a crate in the interact message without a key.

**Comment by imWillX** [comment]
Do you mean {crate-name}? http://crates.hazebyte.com/#/reference/variables
```
core.player_given_crate = {p} &eYou have been given {number} {crate} {crate-name}.
```

```
FoodieKey:
  type: KEY
  item: TRIPWIRE_HOOK 1 name:&c[&6Foodie_&ePack&c]_&f#127 lore:&8Right_click_a_key_chest_to_obtain_rewards!
  animation: NONE
  end-animation: BLANK
  display-name: '(FoodieKey Display Name)'
```
![img](https://i.imgur.com/jk8Q6k9.png)
