### ISSUE TITLE
INSTANTSPELL particle is incorrect.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#261]
CrateReloaded 2.0 ALPHA3

```
    '5':
      class: Original
      particle: INSTANTSPELL
      radiusIncrease: 0.01
      maxRadius: 1.6
      category: PERSISTENT
```

It is showing a giant ball with fire particles instead of the proper INSTANTSPELL particle in 1.12.2 / CrateReloaded 1.x.

Full effects list.
```
  effect:
    '1':
      class: Sound
      sound: ENTITY_BAT_TAKEOFF
      category: END
    '2':
      class: Firework
      category: OPEN
      fireworkType: BALL
    '3':
      class: Sound
      sound: ENTITY_GENERIC_DRINK
      category: OPEN
    '4':
      class: Sound
      sound: UI_BUTTON_CLICK
      category: ANIMATION
    '5':
      class: Original
      particle: INSTANTSPELL
      radiusIncrease: 0.01
      maxRadius: 1.6
      category: PERSISTENT
```

![link](https://i.imgur.com/PmHGxf3.png)
