### ISSUE TITLE
Add sounds for additional crate actions

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#306]
Would be useful if it were possible to have a configurable sound associated with each chest when the player inspects the items in the chest by left clicking, or is pushed back from the chest when they do not have the appropriate key, and for each of the button actions.

For example, two new categories could be added to the crate effect sections, INSPECT and PUSHBACK in crate.yml:

```
AwesomeCrate:
  effect:
    1:
      class: Sound
      category: INSPECT
      sound: BLOCK_CHEST_OPEN
    2:
      class: Sound
      category: PUSHBACK
      sound: ENTITY_PLAYER_BURP
```

And in config.yml, would add parsing of a sound: value from each of the buttons:

```
crate:
  buttons:
    enabled: true

    # Next Button
    # It is used to turn the virtual inventory page
    next: 'arrow 1 name:&aNext_Page lore:&eClick_to_enter_the_next_page. sound:UI_BUTTON_CLICK'

    # Close Button
    # It is used to close the inventory
    close: 'iron_door 1 name:&cExit flag:HIDE_POTION_EFFECTS sound:BLOCK_CHEST_CLOSE'

    # Next Button
    back: 'red_bed 1 name:&4Go_back lore:&eGo_back_to_previous_page. sound:UI_BUTTON_CLICK'

    # Confirmation Menu Buttons
    # Each crate may have an individualized button defined in the crate.yml
    # If no buttons are defined, default buttons will be used
    accept: 'lime_concrete 1 name:&aYes lore:&fClick_here_to_open_{crate}! sound:UI_BUTTON_CLICK'
    decline: 'red_concrete 1 name:&4No sound:UI_BUTTON_CLICK'
```
