### ISSUE TITLE
Add sound to buttons

### ISSUE THREAD

**Issue by imWillX** [Hazebyte/CrateReloaded#383]
#306 
```
crate:
  buttons:
    enabled: true

    # Next Button
    # It is used to turn the virtual inventory page
    next: 'arrow 1 name:&aNext_Page lore:&eClick_to_enter_the_next_page. sound:UI_BUTTON_CLICK'

    # Close Button
    # It is used to close the inventory
    close: 'iron_door 1 name:&cExit flag:HIDE_POTION_EFFECTS sound:BLOCK_CHEST_CLOSE'

    # Next Button
    back: 'red_bed 1 name:&4Go_back lore:&eGo_back_to_previous_page. sound:UI_BUTTON_CLICK'

    # Confirmation Menu Buttons
    # Each crate may have an individualized button defined in the crate.yml
    # If no buttons are defined, default buttons will be used
    accept: 'lime_concrete 1 name:&aYes lore:&fClick_here_to_open_{crate}! sound:UI_BUTTON_CLICK'
    decline: 'red_concrete 1 name:&4No sound:UI_BUTTON_CLICK'
```
