### ISSUE TITLE
Mysterycrate always:() not working

### ISSUE THREAD

**Issue by 0xC1A551C** [Hazebyte/CrateReloaded#397]
I never receive the gold ingot. I tried with 1 reward, 2 reward, different items, switching always:() and unique:() adding chance:() adding or removing the 1 in always:() ect.

1.14.2 mystercrate

```
    reward:
        minimum-rewards: 2
        maximum-rewards: 2
        rewards:
            - 'unique:(),       always:(1),           item:(gold_ingot 32)'
            - 'chance:(1),       unique:(),           item:(iron_ingot 32)'
```
