### ISSUE TITLE
CNPC Issues

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#414]
Putting things here for willydoo

**Server**: Paper 1.12.2
**CR Version**: 2.0.15
**CNPC Ver**: 1.0.1
**Citizens**: 2.0.25 b1676

Issues:

- 1. When you reload crates `/cr reload`, the NPC will forget which crates are set, meaning you need to `/cnpc set` all of your crates on reload. 

- 2. When the issue above occurs, this causes the crate preview window (when multiple crates are set on the same block/npc, CR sends the user select which crate to preview) to create duplicates of the crates which are set. I believe this occurs for both blocks and npcs. 
- 2. https://flamingo.cf/ENa.png

- 3. Rand similar (i think this is fixed)

- 4. I cant get confirmation menu to activate for my mystery crates, or any crates. Here is one of my crates to try with:

```
MS_1:
  type: MYSTERY
  item: MOB_SPAWNER 1 name:&8[&a✪&7✪✪✪✪&8]_&a&lABANDONED_&7&lSPAWNER lore:&f|&7&oRight-click_to_reveal_mob_type!|&a&lAbandoned_Spawner|&7Info:_&fAn_abandoned_spawner_which|&fhas_forgotten_its_identity|&f|&7Possible_Rewards:_|&a┃_&f1&7x_&7Pile_of_dust..|&a┃_&f1&7x_&aZombie_&7Spawner|&a┃_&f1&7x_&aSkeleton_&7Spawner|&a┃_&f1&7x_&aSpider_&7Spawner|&a┃_&f1&7x_&aCave_Spider_&7Spawner|&a┃_&f1&7x_&aBlaze_&7Spawner|&e┃_&f1&7x_&aCreeper_&7Spawner|&c┃_&f2&7x_&a&lABANDONED_&7&lSPAWNER|&c┃_&f1&7x_&9&lABANDONED_&7&lSPAWNER|&c┃_&f1&7x_&5&lABANDONED_&7&lSPAWNER|&f|&a&lDR_&8&l»_&7Consumables
    durability:1
  confirmation:
    enabled: true
    accept-button: LIME_STAINED_GLASS_PANE:5 1 name:&a&lCONFIRM&r
    decline-button: RED_STAINED_GLASS_PANE:14 1 name:&c&lCANCEL&r
  message:
    open: |
      &a&lDR &8&l» &fThe spawner shakes a little bit to reveal..
  reward:
    minimum-rewards: 1
    maximum-rewards: 1
    rewards:
    - 'chance:(10.0), msg:(&a&lDR &8&l» &fDust.. :c)'
```
