### ISSUE TITLE
Typo in the config.yml

### ISSUE THREAD

**Issue by PlayingWithPi** [Hazebyte/CrateReloaded#530]
Latest version (released) of Pro seems to have a typo:
(the `next:`  and  `back:`  have the same comments added)
```yaml
  # Trigger Buttons
  buttons:
    enabled: true

    # Next Button
    # It is used to turn the virtual inventory page
    next: 'ARROW 1 name:&aNext_Page lore:&eClick_to_enter_the_next_page.'

    # Close Button
    # It is used to close the inventory
    close: 'MUSIC_DISC_11 1 name:&4Close! flag:HIDE_POTION_EFFECTS'

    # Next Button
    back: 'RED_BED 1 name:&4&lGo_back lore:&eGo_back_to_previous_page.'
```
