### ISSUE TITLE
``particles`` effect count seems to be ignored in 1.17 update

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#535]
CrateReloaded Pro 2.0.35-1.17
Paper dev 79 (Spigot 1.17)

The ``particles`` count seems to be ignored since the 1.17 update, causing large amount of particle spam around crates. All my crate locations have crazy particles surrounding it now when it use to be fairly miniscule for decoration only. 

On 1.16.5 & pre-1.17 CrateReloaded update, everything is fine. On 1.17 and post-1.17 CrateReloaded update, particles do not behave the same.

![link](https://cdn.discordapp.com/attachments/182180522875682817/860238445002883122/2021-07-01_12.19.11.png)

Blue crate in the background.
```
  effect:
     '5':
       class: Original
       particle: SPELL_INSTANT
       category: PERSISTENT
       particles: 1
       radius: 0.8
       period: 6
```
Yellow crate up front.
```
     '5':
       class: Original
       particle: PORTAL
       category: PERSISTENT
       particles: 1
       radius: 1
```

Pink crate in the far background.
```
     '5':
       class: Original
       particle: PORTAL
       category: PERSISTENT
       particles: 1
       radius: 0.8
       period: 6
```
