### ISSUE TITLE
Claim message appears on login despite not having anything in the claim.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#568]
CrateReloaded Pro v2.1.1

![link](https://i.imgur.com/qHLgfYE.png)

Upgraded from CrateReloaded 2.0.39 to 2.1.1. CrateReloaded is now sending the claim message on every join even if the player does not have anything to claim. Prior behavior it only sent the message if there was something.

```
core.claim_hold = {p} &lHey &l{player-name}&7&l! &7You have &c{number} pending rewards&7. Type &e&l/claim &7to get them!
core.claim_none = {p} You do not have any rewards to claim.
```

```
# Claim
claim:
  # The command prefix. DO NOT MODIFY.
  # ONLY TO BE CHANGED IF PREFIX IS CONFLICTING
  command: 'cr'

  # The maximum amount of rewards a player can claim
  # The maximum amount a player can claim is the minimum of either their inventory space or this limit.
  limit: 15

  # Menu name
  menu: 'Claim Rewards!'

  # If the inventory is full, let the claim manager handle it.
  # Otherwise, it will drop to the ground.
  handle-full-inventory: true

  # Remind users that they have rewards to claim
  reminder:
    # Send a message to the player upon joining the server
    join: true
    # Send a message to the player in an interval
    timer: false
    # Interval in seconds
    period: 900

  # Formatting the items
  format:
    item:
      - '{lore}'
      - '&7Number of Rewards: &6{number}'
      - '&7Received on {date}'
    item-success: '&a&lClaimed!'
```
