### ISSUE TITLE
Particles are no longer displaying correctly.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#569]
CrateReloaded Pro v2.1.1

Upgraded from CrateReloaded 2.0.39 to 2.1.1. Particles are no longer displaying how they use to.

```
  effect:
    '5':
      class: Original
      particle: SPELL_INSTANT
      category: PERSISTENT
      particleCount: 1
      radius: 0.8
      period: 6
```
![link](https://i.imgur.com/xNIPLhi.png)

```
    '5':
      class: Original
      particle: PORTAL
      category: PERSISTENT
      particleCount: 1
      radius: 0.8
      period: 6
```
![link](https://i.imgur.com/dHrPrjI.png)
